/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis2;

/**
 *
 * @author Asus
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hrg1 = new javax.swing.JTextField();
        Hrg2 = new javax.swing.JTextField();
        Hrg3 = new javax.swing.JTextField();
        Hrg4 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 538, 55);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 86, 95, 43);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(63, 147, 95, 43);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(63, 209, 95, 43);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(63, 271, 95, 43);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(63, 332, 95, 50);

        Hrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hrg1ActionPerformed(evt);
            }
        });
        getContentPane().add(Hrg1);
        Hrg1.setBounds(233, 86, 217, 43);

        Hrg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hrg2ActionPerformed(evt);
            }
        });
        getContentPane().add(Hrg2);
        Hrg2.setBounds(233, 148, 217, 43);

        Hrg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hrg3ActionPerformed(evt);
            }
        });
        getContentPane().add(Hrg3);
        Hrg3.setBounds(233, 210, 217, 43);

        Hrg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hrg4ActionPerformed(evt);
            }
        });
        getContentPane().add(Hrg4);
        Hrg4.setBounds(233, 271, 217, 43);

        Diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiskonActionPerformed(evt);
            }
        });
        getContentPane().add(Diskon);
        Diskon.setBounds(233, 333, 217, 50);

        Proses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(92, 401, 87, 38);

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(241, 401, 71, 38);

        Keluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(381, 401, 69, 38);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 457, 538, 188);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Hrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hrg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hrg1ActionPerformed

    private void Hrg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hrg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hrg2ActionPerformed

    private void Hrg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hrg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hrg3ActionPerformed

    private void Hrg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hrg4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hrg4ActionPerformed

    private void DiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiskonActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        int hrg1 = Integer.parseInt(Hrg1.getText());
        int hrg2 = Integer.parseInt(Hrg2.getText());
        int hrg3 = Integer.parseInt(Hrg3.getText());
        int hrg4 = Integer.parseInt(Hrg4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        int TotalBayar ;
        int TotalHarga = hrg1 + hrg2 + hrg3 + hrg4;

        if (diskon == 0){
            TotalBayar = TotalHarga;
            TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 :" + hrg4 + "\n" + "Diskon : " + diskon + 
                    "\n" + "Total Harga : " + TotalHarga + "\n" + "Total Bayar : " + TotalBayar);
        }else if(diskon == 25){
           TotalBayar = TotalHarga * 75/100;
           TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 :" + hrg4 + "\n" + "Diskon : " + diskon + 
                    "\n" + "Total Harga : " + TotalHarga + "\n" + "Total Bayar : " + TotalBayar);
        }else if (diskon == 50){
            TotalBayar = TotalHarga * 50/100;
           TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 :" + hrg4 + "\n" + "Diskon : " + diskon + 
                    "\n" + "Total Harga : " + TotalHarga + "\n" + "Total Bayar : " + TotalBayar);
        }else if (diskon == 75){
            TotalBayar = TotalHarga * 25/100;
           TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 :" + hrg4 + "\n" + "Diskon : " + diskon + 
                    "\n" + "Total Harga : " + TotalHarga + "\n" + "Total Bayar : " + TotalBayar);
        }else if(diskon == 100){
            TotalBayar = TotalHarga * 0;
            TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 :" + hrg4 + "\n" + "Diskon : " + diskon + 
                    "\n" + "Total Harga : " + TotalHarga + "\n" + "Total Bayar : " + TotalBayar);
        }

        
        
//       TA.setText("Harga Barang 1 : " + hrg1 + "\n" + "Harga Barang 2 : " + hrg2 + "\n" + "Harga Barang 3 : " + hrg3 + "\n" + "Harga Barang 4 : " + hrg4 + "\n" +
//                "DIskon :" + diskon + "\n" + "Total Bayar : " + TotalBayar);
    }//GEN-LAST:event_ProsesActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        Hrg1.setText("");
        Hrg2.setText("");
        Hrg3.setText("");
        Hrg4.setText("");
        Diskon.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Hrg1;
    private javax.swing.JTextField Hrg2;
    private javax.swing.JTextField Hrg3;
    private javax.swing.JTextField Hrg4;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
